module.exports = {
  data: {
    results: [
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-11",
        deaths: 827,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-12",
        deaths: 827,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-13",
        deaths: 1266,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-14",
        deaths: 1441,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-15",
        deaths: 1809,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-16",
        deaths: 2158,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-17",
        deaths: 2503,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-18",
        deaths: 2978,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-19",
        deaths: 3405,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-20",
        deaths: 4032,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-21",
        deaths: 4825,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-22",
        deaths: 5476,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-23",
        deaths: 6077,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-24",
        deaths: 6820,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-25",
        deaths: 7503,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-26",
        deaths: 8215,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-27",
        deaths: 9134,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-11",
        deaths: 36,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-12",
        deaths: 40,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-13",
        deaths: 47,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-14",
        deaths: 54,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-15",
        deaths: 63,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-16",
        deaths: 85,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-17",
        deaths: 108,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-18",
        deaths: 118,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-19",
        deaths: 200,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-20",
        deaths: 244,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-21",
        deaths: 307,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-22",
        deaths: 417,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-23",
        deaths: 557,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-24",
        deaths: 706,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-25",
        deaths: 942,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-26",
        deaths: 1209,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-27",
        deaths: 1581,
        __typename: "Result",
      },
    ],
  },
};
