module.exports = {
  data: {
    results: [
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-30",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-1-31",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-3",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-4",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-5",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-6",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-7",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-8",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-9",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-10",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-11",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-12",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-13",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-14",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-15",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-16",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-17",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-18",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-19",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-20",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-21",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-22",
        deaths: 2,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-23",
        deaths: 3,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-24",
        deaths: 7,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-25",
        deaths: 10,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-26",
        deaths: 12,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-27",
        deaths: 17,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-28",
        deaths: 21,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-2-29",
        deaths: 29,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-1",
        deaths: 34,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-2",
        deaths: 52,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-3",
        deaths: 79,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-4",
        deaths: 107,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-5",
        deaths: 148,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-6",
        deaths: 197,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-7",
        deaths: 233,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-8",
        deaths: 366,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-9",
        deaths: 463,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-10",
        deaths: 631,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-11",
        deaths: 827,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-12",
        deaths: 827,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-13",
        deaths: 1266,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-14",
        deaths: 1441,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-15",
        deaths: 1809,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-16",
        deaths: 2158,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-17",
        deaths: 2503,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-18",
        deaths: 2978,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-19",
        deaths: 3405,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-20",
        deaths: 4032,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-21",
        deaths: 4825,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-22",
        deaths: 5476,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-23",
        deaths: 6077,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-24",
        deaths: 6820,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-25",
        deaths: 7503,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-26",
        deaths: 8215,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-27",
        deaths: 9134,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-28",
        deaths: 10023,
        __typename: "Result",
      },
      {
        country: { name: "Italy", __typename: "Country" },
        date: "2020-3-29",
        deaths: 10779,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-30",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-1-31",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-3",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-4",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-5",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-6",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-7",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-8",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-9",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-10",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-11",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-12",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-13",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-14",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-15",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-16",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-17",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-18",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-19",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-20",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-21",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-2-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-3",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-4",
        deaths: 2,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-5",
        deaths: 3,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-6",
        deaths: 5,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-7",
        deaths: 10,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-8",
        deaths: 17,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-9",
        deaths: 28,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-10",
        deaths: 35,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-11",
        deaths: 54,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-12",
        deaths: 55,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-13",
        deaths: 133,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-14",
        deaths: 195,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-15",
        deaths: 289,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-16",
        deaths: 342,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-17",
        deaths: 533,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-18",
        deaths: 623,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-19",
        deaths: 830,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-20",
        deaths: 1043,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-21",
        deaths: 1375,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-22",
        deaths: 1772,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-23",
        deaths: 2311,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-24",
        deaths: 2808,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-25",
        deaths: 3647,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-26",
        deaths: 4365,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-27",
        deaths: 5138,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-28",
        deaths: 5982,
        __typename: "Result",
      },
      {
        country: { name: "Spain", __typename: "Country" },
        date: "2020-3-29",
        deaths: 6803,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-30",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-1-31",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-3",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-4",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-5",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-6",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-7",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-8",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-9",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-10",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-11",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-12",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-13",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-14",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-15",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-16",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-17",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-18",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-19",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-20",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-21",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-2-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-3",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-4",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-5",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-6",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-7",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-8",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-9",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-10",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-11",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-12",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-13",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-14",
        deaths: 2,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-15",
        deaths: 3,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-16",
        deaths: 6,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-17",
        deaths: 7,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-18",
        deaths: 10,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-19",
        deaths: 11,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-20",
        deaths: 16,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-21",
        deaths: 20,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-22",
        deaths: 21,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-23",
        deaths: 25,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-24",
        deaths: 36,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-25",
        deaths: 62,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-26",
        deaths: 77,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-27",
        deaths: 105,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-28",
        deaths: 105,
        __typename: "Result",
      },
      {
        country: { name: "Sweden", __typename: "Country" },
        date: "2020-3-29",
        deaths: 110,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-29",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-30",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-1-31",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-1",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-2",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-3",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-4",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-5",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-6",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-7",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-8",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-9",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-10",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-11",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-12",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-13",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-14",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-15",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-16",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-17",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-18",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-19",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-20",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-21",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-22",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-23",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-24",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-25",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-26",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-27",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-28",
        deaths: 0,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-2-29",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-1",
        deaths: 1,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-2",
        deaths: 6,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-3",
        deaths: 7,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-4",
        deaths: 11,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-5",
        deaths: 12,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-6",
        deaths: 14,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-7",
        deaths: 17,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-8",
        deaths: 21,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-9",
        deaths: 22,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-10",
        deaths: 28,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-11",
        deaths: 36,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-12",
        deaths: 40,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-13",
        deaths: 47,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-14",
        deaths: 54,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-15",
        deaths: 63,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-16",
        deaths: 85,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-17",
        deaths: 108,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-18",
        deaths: 118,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-19",
        deaths: 200,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-20",
        deaths: 244,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-21",
        deaths: 307,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-22",
        deaths: 417,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-23",
        deaths: 557,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-24",
        deaths: 706,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-25",
        deaths: 942,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-26",
        deaths: 1209,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-27",
        deaths: 1581,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-28",
        deaths: 2026,
        __typename: "Result",
      },
      {
        country: { name: "US", __typename: "Country" },
        date: "2020-3-29",
        deaths: 2467,
        __typename: "Result",
      },
    ],
  },
};
